language: node_js
node_js:
  - 12.14.1
cache: yarn

jobs:
  include:
    - stage: test
      env:
        FONT_AWESOME_PRO_AUTH_TOKEN:
          secure: "LNfsHOFqdQA24xl5KBEPSWnSge7JX9kwdCgw4Chsb8Smoqg4BobrT6Nx2efjL+bft8Y33wjDZd+T2uap1ljb29YK3NUYzkI0jCAleNddA/qUDhuRqJq5CCN1obC/2gka4KsviISq9cNcpM4IyBw3HF+m8da+p18XImgDdu/LRMox5qYwSJ9ezqxud+sqnKaxYlDQw5LlwDxspZ9acCBCWwN+bnuUVZ6K0k8o9u5PMqsXGQcYnGXdcXmZLu4WDrg6DfQu9b+1YR/RnvyveMIhIl6WP4rvwnpcFz9p0B5G1katgmp6DOOUjSJ5zVImls0nG35MZ0s1oTt4FE7ZWBCG7Bi7dnYD0Pmy36DuM/W2KcjJre0gUv3Zt5amwC0WSyosgMp4+uHm/R/FZyMr//6IxJLLFlKK5bvK+d3HlHky9dCGZK2UfNWJ/5/UBAmYTfNYave1r+Cir6WMClY3jifbw/SK0QGStKQEg2wnPfCHzYUJ4Fpxy76s1XRxoboWxRY14s1wM7IufrtP/nkMBAJ6qX8178R5nRz3MtoBtfiwxs2+dBRU8Fwypm7N/XBmvquG4a7gn6UDXwdF84eU9+KJ5XTPJnCNzhjA+NptI6IBnNBOmiLzQ+/F5Zud6q1FnI53kqWrvs4rZUNqYy481K3FyodpO3FXpd5kz1semYZEq9o="
      script: 
        - ls -la
        - cd ./client
        - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        - npm config set "//npm.fontawesome.com/:_authToken" $FONT_AWESOME_PRO_AUTH_TOKEN
        - yarn install
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy