language: node_js
node_js:
  - 12.14.1
cache: yarn

services:
  - docker

jobs:
  include:
    - stage: test_client
      env:
        - secure: "IG35XsGEu0eqtoqHoKK0rp2mw40u9PTvC4U+aNJLH9jqinLYgyGeVyFBcL2yUcZgX+/rtZTa6fhxccTwJw7oa89nD5Z+RiNzklwoKm0nkN6jGd5Zu+ane458sFVe3sahGPid7HPOxiVxMzzvbb7d+5Yma+BnoNJt+ojPnaRyZdPs4ueVRptwH7uJTyYF3+c+8zX7/ZmpztA0OqkGOO9R5l4g3D6k2h7+CJsvFc0DJj+b6WXIEwBHQjow3awTeAO2sc7numuF1sYVD5nG2kaCUMMgHHNcPey+G95agcpniEkAOhlp+S10ldyOt7rroe5MybaEyhlr06n2CrmWAIvVxPidVJvQMA3zKZtw+AaMTdKVCtdgnzyxRe468yPmlqCRD8F9rFIB8t/5bY6sxk/KoaJID02UBl7ARbUSfViXnRiiojVuzAbW8GeodrXTvGvL8jZjPas4kedC8V9AxMO6sKSAovaSZbXJC9x3/sEFBfC59j0B566VQphIyLklGBuU8mW3q7y+c5bWrD9M+ojI3TdAWzwPrj7yWq3ivINsLtN6Q3v/NC0seG0UFGeveQELrV14j52f2hABaYy4dLr2OSPPou+DPQZTZG5jUUyipRAedCF3wMp7XuUi74qt+fPiwKE15s7h272g7edBVbTAMMfWYsV5NGOE5F6oGOpMpmA="
      script: 
        - ls -la
        - cd $TRAVIS_BUILD_DIR/client
        - npm config set "@fortawesome:registry" https://npm.fontawesome.com/
        - npm config set "//npm.fontawesome.com/:_authToken" $FONT_AWESOME_PRO_AUTH_TOKEN
        - yarn install
        - yarn run test
    - stage: test_server
      env:
        - NODE_ENV=ci
        - APP_CLIENT_HTTP_SCHEME=http
        - APP_CLIENT_HOST=localhost
        - APP_CLIENT_PORT=3000
        - APP_CLIENT_LOGIN_URI=login
        - DB_USER=root
        - DB_PASSWORD=root
        - DB_HOST=localhost
        - DB_PORT=54320
        - DB_NAME=ci
        - DB_SYNC_WITH_SEQUELIZE=false
        - DB_DIALECT=postgres
        - FAIL_BUILD_IF_SEEDERS_FAIL=true
        - DOCKER_COMPOSE_FILE=docker-compose-ci.yml
      script: 
        - ls -la
        - docker-compose --version
        - docker-compose -f $DOCKER_COMPOSE_FILE up -d
        - docker ps
        - cd $TRAVIS_BUILD_DIR/server
        - yarn install
        - yarn run test:unit
        - yarn run test:int
        - yarn run test:e2e