language: node_js
node_js:
  - 12.14.1
cache: yarn

jobs:
  include:
    - stage: test
      script: 
        - ls -la
        - cd ./client
        - yarn install
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy