apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: codihuston/gairos-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
deploy:
  kubectl:
    manifests:
    - k8s-dev/*.yml