apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: codihuston/gairos-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
    - image: codihuston/gairos-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
        buildArgs:
          FONTAWESOME_NPM_AUTH_TOKEN: "{{.FONTAWESOME_NPM_AUTH_TOKEN}}"
      sync:
        '***/*.js': .
        '***/*.css': .
        '***/*.scss': .
        '***/*.html': .
deploy:
  kubectl:
    manifests:
    - k8s-dev/*.yml